# Generated by Django 5.0.7 on 2024-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.TextField()),
                ("private_key", models.TextField()),
                ("is_ca", models.BooleanField(default=False)),
                ("common_name", models.CharField(max_length=50)),
            ],
        ),
    ]
