# Generated by Django 5.0.7 on 2024-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_certificate_signed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="current_serial",
            field=models.CharField(default="0000000000000000", max_length=20),
            preserve_default=False,
        ),
    ]
