# Generated by Django 5.0.7 on 2024-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0003_certificate_current_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="kind",
            field=models.IntegerField(
                choices=[(0, "CA"), (1, "Device"), (2, "Host name")], default=0
            ),
            preserve_default=False,
        ),
    ]
