# Generated by Django 5.0.7 on 2024-07-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0004_certificate_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="current_serial",
        ),
        migrations.AddField(
            model_name="certificate",
            name="serial",
            field=models.CharField(default="000000000000", max_length=40),
            preserve_default=False,
        ),
    ]
