# Generated by Django 5.0.7 on 2024-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0005_remove_certificate_current_serial_certificate_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="is_used_for_client_auth",
            field=models.BooleanField(
                default=False,
                verbose_name="Can this certificate be used for client authentication?",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="is_ca",
            field=models.BooleanField(
                default=False,
                verbose_name="Can this certificate be used for signing certificates that are meant to sign other certificates?",
            ),
        ),
    ]
