# Generated by Django 5.0.7 on 2024-07-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0007_alter_certificate_is_used_for_client_auth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="kind",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="certificates.certificate",
            ),
        ),
    ]
