# Generated by Django 5.0.7 on 2024-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0008_remove_certificate_kind_alter_certificate_signed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="common_name",
            field=models.CharField(max_length=255),
        ),
    ]
