# Generated by Django 5.0.7 on 2024-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0009_alter_certificate_common_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="can_sign",
            field=models.BooleanField(
                default=False,
                verbose_name="Can this certificate be used for signing other certificates?",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="is_ca",
            field=models.BooleanField(
                default=False,
                verbose_name="Can this certificate be used for signing certificates that sign othercertificates?",
            ),
        ),
    ]
