# Generated by Django 5.0.7 on 2024-07-17 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0010_certificate_can_sign_alter_certificate_is_ca"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("serial", "signed_by")},
        ),
    ]
