# Generated by Django 5.0.7 on 2024-07-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0012_alter_certificate_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="extra_data",
            field=models.TextField(default="{}", verbose_name="Extra data"),
        ),
    ]
