# Generated by Django 5.0.7 on 2024-07-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0005_remove_certificate_current_serial_certificate_serial"),
        ("signing", "0002_signing_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signing",
            name="openssl_conf",
            field=models.TextField(
                help_text="Private keys and certificates will be stored inside $dir/cert.pem and $dir/cert.key.Serial is stored within $dir/serial.New certs dir is stored within $dir/newcerts",
                verbose_name="OpenSSL configuration file",
            ),
        ),
        migrations.CreateModel(
            name="SignatureDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("V", "valid"), ("R", "revoked"), ("E", "expired")],
                        max_length=1,
                    ),
                ),
                ("expiration", models.CharField(max_length=20)),
                ("revocation", models.CharField(default="unknown", max_length=20)),
                ("serial", models.CharField(max_length=20)),
                ("subject_dn", models.CharField(max_length=255)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="certificates.certificate",
                    ),
                ),
                (
                    "signing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="signing.signing",
                    ),
                ),
            ],
        ),
    ]
