# Generated by Django 5.0.7 on 2024-07-16 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signing", "0004_alter_signaturedatabase_revocation_signingfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signing",
            old_name="ca",
            new_name="certificate",
        ),
    ]
