# Generated by Django 5.0.7 on 2024-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0005_rename_ca_signing_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="signing",
            name="next_serial",
            field=models.CharField(
                default="00000000000000",
                max_length=64,
                verbose_name="Next serial to use for signing",
            ),
            preserve_default=False,
        ),
    ]
