# Generated by Django 5.0.7 on 2024-07-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0012_alter_certificate_serial"),
        ("signing", "0008_alter_signing_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaturedatabase",
            name="certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="certificates.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="signaturedatabase",
            name="serial",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="signaturedatabase",
            name="signing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="signing.signing"
            ),
        ),
        migrations.AlterField(
            model_name="signing",
            name="next_serial",
            field=models.CharField(
                max_length=16, verbose_name="Next serial to use for signing"
            ),
        ),
        migrations.AlterField(
            model_name="signing",
            name="openssl_conf",
            field=models.TextField(
                help_text="Take a look at sample attached openssl.conf",
                verbose_name="OpenSSL configuration file",
            ),
        ),
    ]
