# Generated by Django 5.0.7 on 2024-07-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0012_alter_certificate_serial"),
        ("signing", "0009_alter_signaturedatabase_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturedatabase",
            name="signed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signers",
                to="certificates.certificate",
                verbose_name="Certificate that has signed this one",
            ),
        ),
        migrations.AlterField(
            model_name="signaturedatabase",
            name="certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="certificates.certificate",
                verbose_name="Certificate that was issued as a result of this",
            ),
        ),
    ]
